### PR TITLE
Convert to Python3

### PR DESCRIPTION
**Pull request by ralic**
using : find . -name '*.py' | xargs 2to3 -w

### CODE REVIEW

**Comment by samarjeet27** [comment]
Hi, Thanks for showing interest !
The unit tests are not compatible with python3. Please change that as well.

**Comment by samarjeet27** [comment]
This is not passing the unit tests.
Earlier, there was an issue with the travis configuration which has been fixed in a recent commit that's why its showing green.
If you rebase it it won't.

**Comment by ralic** [comment]
It should be ok now.

**Comment by thelehhman** [comment]
Closed in favour of #9

**Pull request closed without merging**
